"use client";

import { use, useEffect } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Latex } from "@/components/latex";
import { useQuizStore } from "@/store/quiz-store";

export default function QuizReportPage({ params }: { params: Promise<{ quizId: string }> }) {
  const { quizId } = use(params);
  const router = useRouter();
  const { status, questions, answers, report, reset } = useQuizStore();

  useEffect(() => {
    if (status === "idle") {
      router.push("/");
    }
  }, [status, router]);

  if (status !== "finished" || !report) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen bg-slate-950 text-slate-300">
        <p className="text-slate-400 mb-4">报告加载中或暂无数据...</p>
        <Button onClick={() => router.push("/")} className="bg-sky-500 hover:bg-sky-600 text-slate-950">
          返回首页
        </Button>
      </div>
    );
  }

  const handleFinish = () => {
    reset();
    router.push("/");
  };

  return (
    <main className="min-h-screen bg-[#050505] text-slate-100 flex flex-col items-center relative overflow-hidden">
      {/* Background Decorative Elements */}
      <div className="absolute top-0 left-0 w-full h-[500px] bg-gradient-to-b from-sky-900/20 to-transparent pointer-events-none" />
      <div className="absolute -top-[10%] -left-[10%] w-[40%] h-[40%] bg-sky-500/10 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute top-[20%] -right-[10%] w-[35%] h-[35%] bg-cyan-500/10 rounded-full blur-[100px] pointer-events-none" />

      <div className="w-full max-w-4xl relative z-10 p-6 sm:p-10 md:p-14">
        {/* Header Section */}
        <div className="mb-12 flex flex-col md:flex-row justify-between items-end gap-8">
          <div className="space-y-2">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-sky-500/10 border border-sky-500/20 text-sky-400 text-xs font-bold tracking-widest uppercase">
              <span className="relative flex h-2 w-2">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-sky-400 opacity-75"></span>
                <span className="relative inline-flex rounded-full h-2 w-2 bg-sky-500"></span>
              </span>
              Learning Analysis
            </div>
            <h1 className="text-4xl md:text-5xl font-black tracking-tight text-white">
              学习分析报告
            </h1>
            <p className="text-slate-400 text-lg">基于 AI 引擎的深度学情画像</p>
          </div>
          <div className="relative group">
            <div className="absolute inset-0 bg-sky-500 blur-2xl opacity-20 group-hover:opacity-40 transition-opacity" />
            <div className="relative flex flex-col items-end">
              <div className="text-6xl md:text-7xl font-black text-white leading-none flex items-baseline gap-1">
                {Math.round(report.total_score)}
                <span className="text-2xl text-slate-500 font-bold uppercase tracking-tighter">pts</span>
              </div>
              <p className="text-sky-400/80 font-bold text-xs mt-2 uppercase tracking-[0.2em]">物理思维达成度</p>
            </div>
          </div>
        </div>

        {/* AI Summary Card - Glassmorphism */}
        <div className="relative mb-16">
          <div className="absolute inset-0 bg-gradient-to-r from-sky-500/10 to-cyan-500/10 rounded-[2rem] blur-xl" />
          <Card className="relative bg-white/[0.03] backdrop-blur-xl border-white/[0.08] rounded-[2rem] shadow-2xl overflow-hidden group">
            <div className="absolute top-0 left-0 w-1 h-full bg-gradient-to-b from-sky-500 to-cyan-500" />
            <CardHeader className="pb-0 flex flex-row items-center gap-4 pt-8">
              <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-sky-500 to-cyan-400 flex items-center justify-center text-2xl shadow-lg shadow-sky-500/20">
                🤖
              </div>
              <div>
                <CardTitle className="text-xl font-bold text-white tracking-tight">AI 综合学情评价</CardTitle>
                <CardDescription className="text-sky-400/60 font-medium text-xs uppercase tracking-wider">Generated by GPT-4 Logic</CardDescription>
              </div>
            </CardHeader>
            <CardContent className="pt-6 pb-10">
              <div className="relative">
                <div className="absolute -left-2 top-0 text-6xl text-white/5 font-serif italic pointer-events-none">“</div>
                <p className="text-slate-300 text-lg leading-relaxed pl-4 font-medium italic">
                  {report.overall_summary || "本次测验表现良好，展现了扎实的基础知识与严谨的逻辑推理。建议继续巩固薄弱环节，探索更深层的物理本质。"}
                </p>
              </div>
            </CardContent>
          </Card>
        </div>

        <h2 className="text-2xl font-bold text-white mb-8 flex items-center gap-3">
          <span className="w-8 h-px bg-slate-800" />
          知识点深度解析
          <span className="bg-slate-800 text-slate-400 text-xs px-2 py-1 rounded ml-2 font-mono">{questions.length} 问题</span>
        </h2>

        {/* Question Cards List */}
        <div className="space-y-12">
          {questions.map((q, idx) => {
            const analysis = report.analysis[q.id];
            const studentInput = answers[q.id] || "未作答";
            const isCorrect = analysis?.is_correct;

            return (
              <div key={q.id} className="relative group">
                <div className="absolute -left-6 top-0 h-full w-px bg-slate-800 group-hover:bg-slate-700 transition-colors" />
                <div className={`absolute -left-[27px] top-6 w-[3px] h-12 rounded-full transition-all duration-500 ${isCorrect ? "bg-emerald-500 shadow-[0_0_15px_rgba(16,185,129,0.5)]" : "bg-rose-500 shadow-[0_0_15px_rgba(244,63,94,0.5)]"}`} />

                <Card className="bg-transparent border-none shadow-none">
                  <CardHeader className="p-0 mb-6">
                    <div className="flex justify-between items-center mb-4">
                      <div className="flex items-center gap-3">
                        <span className="text-slate-500 font-mono text-sm tracking-tighter uppercase">Question</span>
                        <span className="text-2xl font-black text-white">{String(idx + 1).padStart(2, '0')}</span>
                      </div>
                      <div className="flex gap-2">
                        <span className="bg-slate-900 border border-slate-800 text-slate-400 px-3 py-1 rounded-full text-[10px] font-bold tracking-widest uppercase">
                          Difficulty: {q.difficulty || "MID"}
                        </span>
                        <div className={`px-4 py-1 rounded-full text-[10px] font-black tracking-widest uppercase border ${isCorrect
                          ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/20"
                          : "bg-rose-500/10 text-rose-400 border-rose-500/20"
                          }`}>
                          {isCorrect ? "Correct" : "Error Identified"}
                        </div>
                      </div>
                    </div>

                    {/* Question Content Box */}
                    <div className="bg-white/[0.02] border border-white/[0.05] rounded-3xl p-6 sm:p-8 backdrop-blur-sm group-hover:bg-white/[0.04] transition-all">
                      <div className="text-slate-200 text-xl leading-relaxed mb-6">
                        <Latex>{q.content_latex}</Latex>
                      </div>
                      {q.image_url && (
                        <div className="relative rounded-2xl overflow-hidden border border-white/5">
                          <img src={q.image_url} alt="题目配图" className="max-h-64 mx-auto object-contain bg-slate-900/50" />
                        </div>
                      )}
                    </div>
                  </CardHeader>

                  <CardContent className="p-0 space-y-8">
                    {/* Multi-column Layout for Answers */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <div className="relative p-6 rounded-3xl bg-slate-900/40 border border-slate-800 transition-colors hover:border-slate-700">
                        <p className="text-[10px] text-slate-500 font-bold mb-3 uppercase tracking-widest flex items-center gap-2">
                          <span className={`w-1.5 h-1.5 rounded-full ${isCorrect ? "bg-emerald-500" : "bg-rose-500"}`} />
                          你的答案
                        </p>
                        <div className={`text-lg font-bold ${isCorrect ? "text-emerald-400" : "text-rose-400"}`}>
                          {q.question_type === "TRUE_FALSE"
                            ? (studentInput === "true" ? "正确" : studentInput === "false" ? "错误" : studentInput)
                            : studentInput || "未填"}
                        </div>
                      </div>

                      {analysis?.correct_answer_display && q.question_type !== "CHOICE" && q.question_type !== "SINGLE_CHOICE" && q.question_type !== "MULTIPLE_CHOICE" && (
                        <div className="relative p-6 rounded-3xl bg-emerald-500/[0.03] border border-emerald-500/10 transition-colors hover:border-emerald-500/30">
                          <p className="text-[10px] text-emerald-500/70 font-bold mb-3 uppercase tracking-widest flex items-center gap-2">
                            <span className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
                            标准答案
                          </p>
                          <div className="text-lg font-bold text-emerald-400">
                            {q.question_type === "BLANK" ? (
                              <Latex>{analysis.correct_answer_display}</Latex>
                            ) : (
                              analysis.correct_answer_display
                            )}
                          </div>
                        </div>
                      )}
                    </div>

                    {/* Options Breakdown for Choice Questions */}
                    {(q.question_type === "CHOICE" || q.question_type === "SINGLE_CHOICE" || q.question_type === "MULTIPLE_CHOICE") && q.answer_schema?.options && (
                      <div className="space-y-3">
                        <div className="flex items-center gap-4 mb-4">
                          <span className="text-[10px] text-slate-500 font-bold uppercase tracking-widest">选项全景图</span>
                          <div className="flex-1 h-px bg-slate-800" />
                        </div>
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                          {q.answer_schema.options.map((opt: any) => {
                            const isCorrectOption = q.question_type === "MULTIPLE_CHOICE"
                              ? (analysis?.correct_answer_display?.split(",").map((s: string) => s.trim()).includes(opt.label))
                              : (analysis?.correct_answer_display === opt.label);

                            const isStudentSelected = q.question_type === "MULTIPLE_CHOICE"
                              ? (studentInput.split(",").map((s: string) => s.trim()).includes(opt.label))
                              : (studentInput === opt.label);

                            return (
                              <div
                                key={opt.label}
                                className={`flex items-start gap-4 p-4 rounded-2xl border transition-all duration-300 ${isCorrectOption
                                  ? "bg-emerald-500/10 border-emerald-500/40"
                                  : isStudentSelected && !isCorrect
                                    ? "bg-rose-500/10 border-rose-500/40"
                                    : "bg-white/[0.01] border-white/[0.05] hover:border-white/[0.15]"
                                  }`}
                              >
                                <div className={`flex-shrink-0 w-8 h-8 rounded-xl flex items-center justify-center font-black text-xs border ${isCorrectOption
                                  ? "bg-emerald-500 text-slate-950 border-emerald-400"
                                  : "bg-slate-800 text-slate-400 border-slate-700"
                                  }`}>
                                  {opt.label}
                                </div>
                                <div className={`flex-1 text-sm font-medium ${isCorrectOption ? "text-emerald-300" : isStudentSelected ? "text-rose-300" : "text-slate-400"}`}>
                                  <Latex>{opt.text}</Latex>
                                </div>
                                {(isCorrectOption || isStudentSelected) && (
                                  <div className="flex-shrink-0">
                                    {isCorrectOption ? (
                                      <div className="w-5 h-5 rounded-full bg-emerald-500 flex items-center justify-center text-[10px] text-slate-950">✓</div>
                                    ) : (
                                      <div className="w-5 h-5 rounded-full bg-rose-500 flex items-center justify-center text-[10px] text-slate-950">✕</div>
                                    )}
                                  </div>
                                )}
                              </div>
                            );
                          })}
                        </div>
                      </div>
                    )}

                    {/* AI Professor Feedback Bubble */}
                    {analysis?.feedback && (
                      <div className="relative pt-4 pl-12">
                        <div className="absolute left-0 top-6 w-10 h-10 rounded-2xl bg-sky-500/10 border border-sky-500/20 flex items-center justify-center text-xl grayscale-[0.5] group-hover:grayscale-0 transition-all">
                          👨‍🏫
                        </div>
                        <div className="relative bg-sky-500/5 p-6 rounded-3xl border border-sky-500/10 shadow-sm transition-all group-hover:bg-sky-500/[0.08]">
                          <div className="absolute -left-2 top-4 w-4 h-4 bg-sky-950 border-l border-b border-sky-500/10 rotate-45" />
                          <div className="flex items-center gap-2 mb-3">
                            <span className="text-[10px] text-sky-400 font-black uppercase tracking-widest">导师点评</span>
                            {analysis?.error_tag && analysis.error_tag !== "CORRECT" && (
                              <span className="bg-rose-500/20 text-rose-400 px-2 py-0.5 rounded text-[10px] font-bold border border-rose-500/30">
                                {analysis.error_tag}
                              </span>
                            )}
                          </div>
                          <div className="text-slate-300 text-sm leading-relaxed prose prose-invert max-w-none">
                            <Latex>{analysis.feedback}</Latex>
                          </div>
                        </div>
                      </div>
                    )}
                  </CardContent>
                </Card>
              </div>
            );
          })}
        </div>

        {/* Final Action Bar */}
        <div className="mt-24 mb-20 flex flex-col items-center gap-6">
          <div className="w-16 h-px bg-gradient-to-r from-transparent via-slate-700 to-transparent" />
          <Button
            onClick={handleFinish}
            size="lg"
            className="group relative h-16 px-12 rounded-full bg-white text-slate-950 font-black text-xl hover:bg-white hover:scale-105 transition-all overflow-hidden"
          >
            <div className="absolute inset-0 bg-gradient-to-r from-sky-400 to-cyan-400 opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
            <span className="relative z-10">完成练习并返回首页</span>
          </Button>
          <p className="text-slate-500 text-sm font-medium">数据已同步至你的学习档案</p>
        </div>
      </div>
    </main>
  );
}
